#cloud-config
autoinstall:
  version: 1
  snaps:
  - name: firefox
  - name: gnome-3-38-2004
  - name: gtk-common-themes
  - name: snap-store
  - name: snapd-desktop-integration
  identity:
    hostname: devops-workstation
    username: tey1ch
    password: '$6$7liDVczxynV7WOr5$g.QQ/QbiP7Vb2YiO/Vhp0QBViXWiexMKXBj/Q2C15nT2jwYaTCccT/vi0woz8g3DfOAv1eVca8t3aXAFdj56R/'
  ssh:
    install-server: true
    allow-pw: true
  storage:
    layout:
      name: lvm
  packages:
    - ubuntu-desktop
    - docker.io
    - docker-compose
    - kubectl
    - kubelet
    - kubeadm
    - terraform
    - ansible
    - git
    - curl
    - wget
    - python3
    - python3-pip
    - openjdk-11-jdk
    - maven
    - gradle
  early-commands:
    - echo 'linux-generic-hwe-22.04' > /run/kernel-meta-package
  late-commands:
    - >-
      curtin in-target --
      sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub

    # Let NetworkManager handle network
    - rm /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml

    # Remove default filesystem and related tools not used with the suggested
    # 'direct' storage layout.  These may yet be required if different
    # partitioning schemes are used.
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs

    # Remove other packages present by default in Ubuntu Server but not
    # normally present in Ubuntu Desktop.
    - >-
      curtin in-target -- apt-get remove -y
      ubuntu-server ubuntu-server-minimal
      binutils byobu curl dmeventd finalrd gawk
      kpartx mdadm ncurses-term needrestart open-iscsi openssh-server
      sg3-utils ssh-import-id sssd thin-provisioning-tools vim tmux
      sosreport screen open-vm-tools motd-news-config lxd-agent-loader
      landscape-common htop git fonts-ubuntu-console ethtool

    # Keep cloud-init, as it performs some of the installation on first boot.
    - curtin in-target -- apt-get install -y cloud-init

